import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './Provider'
import Nav from '@/components/Nav'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Hackathon Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Nav/>
        {children}
        </AuthProvider>
        </body>
    </html>
  )
}
