import { Inter } from 'next/font/google'
import './globals.css'
import { AuthProvider } from './Provider'
import Nav from '@/components/Nav'

import { ReduxProvider } from './redux/provider'
import Coin from '@/components/Coin'
export const metadata = {
  title: 'Hackathon Project',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-hidden" style={{backgroundImage:'url(assets/TrashBackground.jpg)', backgroundSize:"cover"}}>
        <ReduxProvider>
          <AuthProvider>
            <Nav/>
            <Coin/>
          {children}
          </AuthProvider>
        </ReduxProvider>
        </body>
    </html>
  )
}
